# -*- coding: utf-8 -*-
"""Hello

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABgoQIwh7dVA-uACo1q-kb8IzgS-g1EE
"""

# Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import streamlit as st
from streamlit.logger import get_logger

LOGGER = get_logger(__name__)


def run():
    st.set_page_config(
        page_title="Hello",
        page_icon="👋",
    )

    st.write("# Andrew Burk's ECON 8320 Semester Project")

    st.markdown(
        """
        This dashboard will allow you to examine demographic variables
        based on union membership.

        In order to do this chose a metro area from the drop down
        and the line graphs will be populated with the chosen city's
        information.

        The demographics chosen for this demonstration are:
        - PEERNLAB union member,y/n
        - HEFAMINC Household-total family income in past 12 month
        - HETENURE Household-own/rent living quarters;
        - HRHTYPE Household-type of family/single individual;
        - PEEDUCA Demographics-highest level of school completed;
        - PRFTLF Labor Force-full time/part-time;
        - PTERNH1O Earnings-hourly pay rate,amount

        Data is from Current Population Survey from the US Census
    """
    )


if __name__ == "__main__":
    run()
